use crate::io_models::models::ExternalSecret;
use serde::Serialize;
use std::collections::BTreeMap;
use uuid::Uuid;

/// One entry within an ESO ExternalSecret object (a single key/value pair to sync).
#[derive(Serialize, Debug, Clone)]
pub struct ExternalSecretEntry {
    /// The environment variable name / key in the resulting k8s Secret.
    pub env_var_key: String,
    /// The key/path in the remote secret manager.
    pub remote_key: String,
    /// Absolute mount path (e.g. `/tmp/db.txt`). Present only for file-mounted entries.
    pub mount_path: Option<String>,
    /// Relative mount path without leading `/` (e.g. `tmp/db.txt`). Used for k8s `subPath` and
    /// `items[].path`. Present only when `mount_path` is Some.
    pub mount_path_relative: Option<String>,
    /// Pre-computed k8s volume name. Present only when `mount_path` is Some.
    pub volume_name: Option<String>,
}

/// A group of external secret entries that share the same ClusterSecretStore, mapping to one ESO
/// ExternalSecret object and one generated k8s Secret.
#[derive(Serialize, Debug, Clone)]
pub struct ExternalSecretGroup {
    /// Name of the ESO ExternalSecret k8s object: `{prefix}-{service_short_id}-{access_id}`.
    pub external_secret_kube_name: String,
    /// The name of the Secret generated by the External Secret
    pub secret_name: String,
    /// Name of the ClusterSecretStore to target: `store-{full_access_uuid}`.
    pub store_name: String,
    /// Individual secret entries (each becomes one `.spec.data` item in the ESO object).
    pub entries: Vec<ExternalSecretEntry>,
}

/// Groups raw external secret entries by their `secret_manager_access_id`, producing one
/// [`ExternalSecretGroup`] per unique store (which maps to one ESO ExternalSecret object).
///
/// Both the ESO `ExternalSecret` object name and the generated k8s `Secret` name follow the
/// pattern `{prefix}-{service_short_id}-{access_id}`, where `prefix` is derived from the first
/// dash-separated component of `kube_name` (e.g. `"app"` from `"app-zf8e21411-my-service"`).
pub fn build_external_secret_groups(
    kube_name: &str,
    external_secrets: BTreeMap<String, ExternalSecret>,
) -> Vec<ExternalSecretGroup> {
    let mut by_access: BTreeMap<Uuid, Vec<(String, ExternalSecret)>> = BTreeMap::new();
    for (key, info) in external_secrets {
        by_access
            .entry(info.secret_manager_access_id)
            .or_default()
            .push((key, info));
    }

    by_access
        .into_iter()
        .map(|(access_id, entries)| {
            let mut mount_idx: usize = 0;
            let entries = entries
                .into_iter()
                .map(|(key, info)| {
                    let (mount_path_relative, volume_name) = match &info.mount_path {
                        Some(p) => {
                            let relative = p.trim_start_matches('/').to_string();
                            let vol_name = format!("ext-{access_id}-{mount_idx}");
                            mount_idx += 1;
                            (Some(relative), Some(vol_name))
                        }
                        None => (None, None),
                    };
                    let remote_key = info.external_secret_name;
                    ExternalSecretEntry {
                        env_var_key: key,
                        remote_key,
                        mount_path: info.mount_path,
                        mount_path_relative,
                        volume_name,
                    }
                })
                .collect();
            let external_secret_name = format!("{kube_name}-{access_id}");
            // INFO (qov-1569) Always add random part because we always make ESO generating a new target kube secret
            let random_part = &Uuid::new_v4().to_string()[0..8];
            let secret_name = format!("{}-{}", external_secret_name, random_part);
            ExternalSecretGroup {
                external_secret_kube_name: external_secret_name,
                secret_name,
                store_name: format!("store-{access_id}"),
                entries,
            }
        })
        .collect()
}
