/// DO NOT MANUALLY EDIT THIS FILE. IT IS AUTO-GENERATED BY INSTANCES FETCHER APP
/// https://gitlab.com/qovery/backend/rust-backend/instances-fetcher
///
/// Returns the availability zones for each Azure location.
/// Data sourced from Azure Management API: GET /subscriptions/{id}/locations
///
/// This is a bootstrap version. Once the instances-fetcher pipeline runs,
/// it will replace this file with dynamically fetched zone data.
use crate::environment::models::ToCloudProviderFormat;

use super::locations::{AzureLocation, AzureZone};

impl AzureLocation {
    /// Returns the availability zones for this Azure location.
    pub fn zones(&self) -> &[AzureZone] {
        match self.to_cloud_provider_format() {
            "australiaeast" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "austriaeast" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "brazilsouth" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "canadacentral" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "centralindia" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "centralus" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "eastasia" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "eastus" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "eastus2" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "francecentral" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "germanywestcentral" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "indonesiacentral" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "israelcentral" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "italynorth" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "japaneast" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "koreacentral" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "mexicocentral" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "newzealandnorth" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "northeurope" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "norwayeast" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "polandcentral" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "qatarcentral" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "southafricanorth" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "southcentralus" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "southeastasia" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "spaincentral" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "swedencentral" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "switzerlandnorth" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "uaenorth" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "uksouth" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "westeurope" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "westus2" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            "westus3" => &[AzureZone::One, AzureZone::Two, AzureZone::Three],
            _ => &[AzureZone::One],
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_known_3_zone_locations() {
        assert_eq!(
            AzureLocation::EastUS.zones(),
            &[AzureZone::One, AzureZone::Two, AzureZone::Three]
        );
        assert_eq!(
            AzureLocation::WestEurope.zones(),
            &[AzureZone::One, AzureZone::Two, AzureZone::Three]
        );
        assert_eq!(
            AzureLocation::NorthEurope.zones(),
            &[AzureZone::One, AzureZone::Two, AzureZone::Three]
        );
    }

    #[test]
    fn test_single_zone_locations() {
        assert_eq!(AzureLocation::AustraliaCentral.zones(), &[AzureZone::One]);
        assert_eq!(AzureLocation::FranceSouth.zones(), &[AzureZone::One]);
    }
}
