image: public.ecr.aws/r3m4q3r9/qovery-ci:34ad865-f60c822

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
  WORKSPACE_ROOT_DIR: /builds/qovery/qovery-engine
  CARGO_HOME: $WORKSPACE_ROOT_DIR/.cargo
  GIT_DEPTH: 10

#cache: &global_cache
#  key: ${CI_COMMIT_REF_SLUG}
#  paths:
#    - $CARGO_HOME
#    - $WORKSPACE_ROOT_DIR/target
#  policy: pull

services:
  - docker:dind

stages:
  - build
  - tests
  - build
  - release
  - deploy

#
# Merge request only
#

linter-mr:
  stage: build
  retry: 0
  script:
    - ./helper.sh lint
  when: always
  tags:
    - 2cpu-4gmem-0g
  only:
    - merge_requests
  interruptible: true

build-mr:
  stage: build
  retry: 0
  script:
    - ./helper.sh build
  when: always
  tags:
    - 2cpu-4gmem-0g
  only:
    - merge_requests
  interruptible: true

all-self-hosted-mr:
  stage: tests
  retry: 0
  script:
    - ./helper.sh all_self_hosted
  only:
  - merge_requests
  when: always
  tags:
    - 2cpu-4gmem-0g
  except:
    variables:
      - $CI_MERGE_REQUEST_TITLE =~ /^WIP:/
      - $CI_MERGE_REQUEST_TITLE =~ /^Draft:/
  dependencies:
    - linter-mr
    - build-mr
  artifacts:
    when: always
    reports:
      junit: /builds/qovery/qovery-engine/cloned-engine/results.xml
    paths:
      - /builds/qovery/qovery-engine/gitlab-log-utilities
      - /builds/qovery/qovery-engine/.qovery-workspace
    expire_in: 1 week
  interruptible: true

all-managed-services-mr:
  stage: tests
  retry: 0
  script:
    - ./helper.sh all_managed_services
  only:
    - merge_requests
  when: manual
  tags:
    - 2cpu-4gmem-0g
  except:
    variables:
      - $CI_MERGE_REQUEST_TITLE =~ /^WIP:/
      - $CI_MERGE_REQUEST_TITLE =~ /^Draft:/
  dependencies:
    - linter-mr
    - build-mr
  artifacts:
    when: always
    reports:
      junit: /builds/qovery/qovery-engine/cloned-engine/results.xml
    paths:
      - /builds/qovery/qovery-engine/gitlab-log-utilities
      - /builds/qovery/qovery-engine/.qovery-workspace
    expire_in: 1 week
  interruptible: true

test-all-mr:
  stage: tests
  retry: 0
  script:
    - ./helper.sh test_all
  only:
    - merge_requests
  dependencies:
    - linter-mr
    - build-mr
  when: manual
  tags:
    - qovery-2cpu-12gb
  except:
    variables:
      - $CI_MERGE_REQUEST_TITLE =~ /^WIP:/
      - $CI_MERGE_REQUEST_TITLE =~ /^Draft:/
  artifacts:
    when: always
    reports:
      junit: /builds/qovery/qovery-engine/cloned-engine/results.xml
    paths:
      - /builds/qovery/qovery-engine/gitlab-log-utilities
      - /builds/qovery/qovery-engine/.qovery-workspace
    expire_in: 1 week
  interruptible: true

#
# Dev branch
#

linter:
  stage: build
  retry: 0
  script:
    - ./helper.sh lint
  when: always
  tags:
    - 7cpu-4gmem-0g
  only:
    refs:
      - dev
  interruptible: true

build:
  stage: build
  retry: 0
  script:
    - ./helper.sh build
#  cache:
#    <<: *global_cache
#    policy: pull-push
  when: always
  tags:
    - 7cpu-4gmem-0g
  only:
    refs:
      - dev

dev-release-image:
  stage: build
  retry: 1
  script:
    - ./helper.sh new_release
  tags:
    - 2cpu-4gmem-0g
  when: manual
  only:
    refs:
      - dev

aws-infra:
  stage: tests
  retry: 0
  script:
    - ./helper.sh aws_infra
  dependencies:
    - linter
    - build
  when: always
  tags:
    - 2cpu-4gmem-0g
  only:
    refs:
      - dev
    variables:
      - $TESTS_TO_RUN =~ /test-aws-infra/
      - $TESTS_TO_RUN =~ /test-aws-all/
      - $TESTS_TO_RUN =~ /test-all/
  artifacts:
    when: always
    reports:
      junit: /builds/qovery/qovery-engine/cloned-engine/results.xml
    paths:
      - /builds/qovery/qovery-engine/gitlab-log-utilities
      - /builds/qovery/qovery-engine/.qovery-workspace
    expire_in: 2 week
  interruptible: true

aws-managed-services:
  stage: tests
  retry: 0
  script:
    - ./helper.sh aws_managed_services
  dependencies:
    - linter
    - build
  tags:
    - 2cpu-12gmem-0g
  when: always
  only:
    refs:
      - dev
    variables:
      - $TESTS_TO_RUN =~ /test-aws-managed-services/
      - $TESTS_TO_RUN =~ /test-aws-all/
      - $TESTS_TO_RUN =~ /test-all/
  artifacts:
    when: always
    reports:
      junit: /builds/qovery/qovery-engine/cloned-engine/results.xml
    paths:
      - /builds/qovery/qovery-engine/gitlab-log-utilities
      - /builds/qovery/qovery-engine/.qovery-workspace
    expire_in: 2 week
  interruptible: true

aws-self-hosted:
  stage: tests
  retry: 0
  script:
    - ./helper.sh aws_self_hosted
  dependencies:
    - linter
    - build
  tags:
    - 2cpu-12gmem-0g
  when: always
  only:
    refs:
      - dev
    variables:
      - $TESTS_TO_RUN =~ /test-aws-self-hosted/
      - $TESTS_TO_RUN =~ /test-aws-all/
      - $TESTS_TO_RUN =~ /test-all/
  artifacts:
    when: always
    reports:
      junit: /builds/qovery/qovery-engine/cloned-engine/results.xml
    paths:
      - /builds/qovery/qovery-engine/gitlab-log-utilities
      - /builds/qovery/qovery-engine/.qovery-workspace
    expire_in: 2 week
  interruptible: true

#
# Main branch
#

main-release-image:
  stage: release
  retry: 1
  script:
    - ./helper.sh new_release
  tags:
    - 7cpu-12gmem-0g
  only:
    refs:
      - main

main-set-ga:
  stage: deploy
  retry: 2
  script:
    - ./helper.sh set_release_ga
  when: manual
  only:
    refs:
      - main

main-deploy-engine-infra:
  stage: deploy
  retry: 0
  script:
    - ./helper.sh release_to_prod
  when: manual
  only:
    refs:
      - main
