image: public.ecr.aws/r3m4q3r9/qovery-ci:df1e5cb-6d6f36c

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_BUILDKIT: 1
  DOCKER_TLS_CERTDIR: ""
  WORKSPACE_ROOT_DIR: $CI_PROJECT_DIR
  CARGO_HOME: $WORKSPACE_ROOT_DIR/.cargo
  GIT_DEPTH: 10
  ROLLBACK_IMAGE: ""

services:
  - docker:dind

stages:
  - build-and-lint
  - local-test
  - tests
  - upgrade-dev
  - e2e-tests
  - downgrade-dev
  - release
  - deploy
  - deploy-all-clusters

#
# Merge request only
#

gitguardian-mr:
  stage: build-and-lint
  image: gitguardian/ggshield:latest
  retry: 0
  when: always
  script: ggshield scan ci
  tags:
    - vm-250mcpu-1gmem-0g
  only:
    - merge_requests
  interruptible: true

build-and-lint-mr:
  stage: build-and-lint
  retry: 0
  script:
    - ./helper.sh lint
    - ./helper.sh build
  when: always
  tags:
    - bm-2cpu-4gmem-0g
  only:
    - merge_requests
  interruptible: true

release-image-mr:
  stage: build-and-lint
  retry: 1
  script:
    - ./helper.sh new_release
  tags:
    - bm-7cpu-4gmem-0g
  when: manual
  only:
  - merge_requests
  interruptible: true

unit-tests-mr:
  stage: tests
  retry: 0
  script:
    - ./helper.sh unit_tests
  only:
    - merge_requests
  when: always
  tags:
    - vm-2cpu-4gmem-0g
  except:
    variables:
      - $CI_MERGE_REQUEST_TITLE =~ /^WIP:/
      - $CI_MERGE_REQUEST_TITLE =~ /^Draft:/
  dependencies:
    - build-and-lint-mr
  artifacts:
    when: always
    reports:
      junit: $CI_PROJECT_DIR/cloned-engine/results.xml
    paths:
      - $CI_PROJECT_DIR/gitlab-log-utilities
      - $CI_PROJECT_DIR/.qovery-workspace
    expire_in: 1 week
  interruptible: true

all-self-hosted-mr:
  stage: tests
  retry: 0
  timeout: 3 hours
  script:
    - ./helper.sh all_self_hosted
  only:
  - merge_requests
  when: always
  tags:
    - vm-2cpu-4gmem-0g
  except:
    variables:
      - $CI_MERGE_REQUEST_TITLE =~ /^WIP:/
      - $CI_MERGE_REQUEST_TITLE =~ /^Draft:/
  dependencies:
    - build-and-lint-mr
  artifacts:
    when: always
    reports:
      junit: $CI_PROJECT_DIR/cloned-engine/results.xml
    paths:
      - $CI_PROJECT_DIR/gitlab-log-utilities
      - $CI_PROJECT_DIR/.qovery-workspace
    expire_in: 1 week
  interruptible: true

all-managed-services-mr:
  stage: tests
  retry: 0
  timeout: 3 hours
  script:
    - ./helper.sh all_managed_services
  only:
    - merge_requests
  when: manual
  tags:
    - vm-2cpu-4gmem-0g
  except:
    variables:
      - $CI_MERGE_REQUEST_TITLE =~ /^WIP:/
      - $CI_MERGE_REQUEST_TITLE =~ /^Draft:/
  dependencies:
    - build-and-lint-mr
  artifacts:
    when: always
    reports:
      junit: $CI_PROJECT_DIR/cloned-engine/results.xml
    paths:
      - $CI_PROJECT_DIR/gitlab-log-utilities
      - $CI_PROJECT_DIR/.qovery-workspace
    expire_in: 1 week
  interruptible: true

test-local:
  stage: local-test
  before_script:
    - docker/wait_docker_available.sh
  script:
    - just test_local_stack $DOCKER_HOST
  only:
    refs:
      - dev
  dependencies:
    - build-and-lint-mr
  when: always

  tags:
    - vm-2cpu-4gmem-0g

test-all-mr:
  stage: tests
  retry: 0
  timeout: 5 hours
  script:
    - ./helper.sh test_all
  only:
    - merge_requests
  dependencies:
    - build-and-lint-mr
  when: manual
  tags:
    - bm-qovery-2cpu-12gb
  except:
    variables:
      - $CI_MERGE_REQUEST_TITLE =~ /^WIP:/
      - $CI_MERGE_REQUEST_TITLE =~ /^Draft:/
  artifacts:
    when: always
    reports:
      junit: $CI_PROJECT_DIR/cloned-engine/results.xml
    paths:
      - $CI_PROJECT_DIR/gitlab-log-utilities
      - $CI_PROJECT_DIR/.qovery-workspace
    expire_in: 1 week
  interruptible: true


#
# Dev branch
#

gitguardian-dev:
  stage: build-and-lint
  image: gitguardian/ggshield:latest
  retry: 0
  when: always
  script: ggshield scan ci
  tags:
    - vm-250mcpu-1gmem-0g
  only:
    refs:
      - dev
  interruptible: true

build-and-lint:
  stage: build-and-lint
  retry: 0
  script:
    - ./helper.sh lint
    - ./helper.sh build
  when: always
  tags:
    - bm-7cpu-4gmem-0g
  only:
    refs:
      - dev
  interruptible: true

dev-release-image:
  stage: build-and-lint
  retry: 1
  script:
    - ./helper.sh new_release
  tags:
    - bm-7cpu-4gmem-0g
  when: manual
  only:
    refs:
      - dev

unit-tests:
  stage: tests
  retry: 0
  script:
    - ./helper.sh unit_tests
  dependencies:
    - build-and-lint
  when: always
  tags:
    - vm-2cpu-4gmem-0g
  only:
    refs:
      - dev
    variables:
      - $TESTS_TO_RUN =~ /test-units/
  artifacts:
    when: always
    reports:
      junit: $CI_PROJECT_DIR/cloned-engine/results.xml
    paths:
      - $CI_PROJECT_DIR/gitlab-log-utilities
      - $CI_PROJECT_DIR/.qovery-workspace
    expire_in: 2 week
  interruptible: true

aws-whole-enchilada:
  stage: tests
  retry: 0
  timeout: 3 hours
  script:
    - ./helper.sh aws_whole_enchilada
  dependencies:
    - build-and-lint
  when: always
  tags:
    - vm-2cpu-4gmem-0g
  only:
    refs:
      - dev
    variables:
      - $TESTS_TO_RUN =~ /test-aws-whole-enchilada/
      - $TESTS_TO_RUN =~ /test-aws-all/
      - $TESTS_TO_RUN =~ /test-all/
  artifacts:
    when: always
    reports:
      junit: $CI_PROJECT_DIR/cloned-engine/results.xml
    paths:
      - $CI_PROJECT_DIR/gitlab-log-utilities
      - $CI_PROJECT_DIR/.qovery-workspace
    expire_in: 2 week
  interruptible: true

aws-infra:
  stage: tests
  retry: 0
  timeout: 3 hours
  script:
    - ./helper.sh aws_infra
  dependencies:
    - build-and-lint
  when: always
  tags:
    - vm-2cpu-4gmem-0g
  only:
    refs:
      - dev
    variables:
      - $TESTS_TO_RUN =~ /test-aws-infra/
      - $TESTS_TO_RUN =~ /test-aws-all/
      - $TESTS_TO_RUN =~ /test-all/
  artifacts:
    when: always
    reports:
      junit: $CI_PROJECT_DIR/cloned-engine/results.xml
    paths:
      - $CI_PROJECT_DIR/gitlab-log-utilities
      - $CI_PROJECT_DIR/.qovery-workspace
    expire_in: 2 week
  interruptible: true

aws-managed-services:
  stage: tests
  retry: 0
  timeout: 3 hours
  script:
    - ./helper.sh aws_managed_services
  dependencies:
    - build-and-lint
  tags:
    - vm-2cpu-4gmem-0g
  when: always
  only:
    refs:
      - dev
    variables:
      - $TESTS_TO_RUN =~ /test-aws-managed-services/
      - $TESTS_TO_RUN =~ /test-aws-all/
      - $TESTS_TO_RUN =~ /test-all/
  artifacts:
    when: always
    reports:
      junit: $CI_PROJECT_DIR/cloned-engine/results.xml
    paths:
      - $CI_PROJECT_DIR/gitlab-log-utilities
      - $CI_PROJECT_DIR/.qovery-workspace
    expire_in: 2 week
  interruptible: true

aws-self-hosted:
  stage: tests
  retry: 0
  timeout: 3 hours
  script:
    - ./helper.sh aws_self_hosted
  dependencies:
    - build-and-lint
  tags:
    - vm-2cpu-12gmem-0g
  when: always
  only:
    refs:
      - dev
    variables:
      - $TESTS_TO_RUN =~ /test-aws-self-hosted/
      - $TESTS_TO_RUN =~ /test-aws-all/
      - $TESTS_TO_RUN =~ /test-all/
  artifacts:
    when: always
    reports:
      junit: $CI_PROJECT_DIR/cloned-engine/results.xml
    paths:
      - $CI_PROJECT_DIR/gitlab-log-utilities
      - $CI_PROJECT_DIR/.qovery-workspace
    expire_in: 2 week
  interruptible: true

do-whole-enchilada:
  stage: tests
  retry: 0
  timeout: 3 hours
  script:
    - ./helper.sh do_whole_enchilada
  dependencies:
    - build-and-lint
  when: always
  tags:
    - vm-2cpu-4gmem-0g
  only:
    refs:
      - dev
    variables:
      - $TESTS_TO_RUN =~ /test-do-whole-enchilada/
      - $TESTS_TO_RUN =~ /test-do-all/
      - $TESTS_TO_RUN =~ /test-all/
  artifacts:
    when: always
    reports:
      junit: $CI_PROJECT_DIR/cloned-engine/results.xml
    paths:
      - $CI_PROJECT_DIR/gitlab-log-utilities
      - $CI_PROJECT_DIR/.qovery-workspace
    expire_in: 2 week
  interruptible: true

do-infra:
  stage: tests
  retry: 0
  timeout: 3 hours
  script:
    - ./helper.sh do_infra
  dependencies:
    - build-and-lint
  when: always
  tags:
    - vm-2cpu-4gmem-0g
  only:
    refs:
      - dev
    variables:
      - $TESTS_TO_RUN =~ /test-do-infra/
      - $TESTS_TO_RUN =~ /test-do-all/
      - $TESTS_TO_RUN =~ /test-all/
  artifacts:
    when: always
    reports:
      junit: $CI_PROJECT_DIR/cloned-engine/results.xml
    paths:
      - $CI_PROJECT_DIR/gitlab-log-utilities
      - $CI_PROJECT_DIR/.qovery-workspace
    expire_in: 2 week
  interruptible: true

do-managed-services:
  stage: tests
  retry: 0
  timeout: 3 hours
  script:
    - ./helper.sh do_managed_services
  dependencies:
    - build-and-lint
  tags:
    - vm-2cpu-4gmem-0g
  when: always
  only:
    refs:
      - dev
    variables:
      - $TESTS_TO_RUN =~ /test-do-managed-services/
      - $TESTS_TO_RUN =~ /test-do-all/
      - $TESTS_TO_RUN =~ /test-all/
  artifacts:
    when: always
    reports:
      junit: $CI_PROJECT_DIR/cloned-engine/results.xml
    paths:
      - $CI_PROJECT_DIR/gitlab-log-utilities
      - $CI_PROJECT_DIR/.qovery-workspace
    expire_in: 2 week
  interruptible: true

do-self-hosted:
  stage: tests
  retry: 0
  timeout: 3 hours
  script:
    - ./helper.sh do_self_hosted
  dependencies:
    - build-and-lint
  tags:
    - vm-2cpu-12gmem-0g
  when: always
  only:
    refs:
      - dev
    variables:
      - $TESTS_TO_RUN =~ /test-do-self-hosted/
      - $TESTS_TO_RUN =~ /test-do-all/
      - $TESTS_TO_RUN =~ /test-all/
  artifacts:
    when: always
    reports:
      junit: $CI_PROJECT_DIR/cloned-engine/results.xml
    paths:
      - $CI_PROJECT_DIR/gitlab-log-utilities
      - $CI_PROJECT_DIR/.qovery-workspace
    expire_in: 2 week
  interruptible: true

scw-whole-enchilada:
    stage: tests
    retry: 0
    script:
      - ./helper.sh scw_whole_enchilada
    dependencies:
      - build-and-lint
    when: always
    tags:
      - vm-2cpu-4gmem-0g
    only:
      refs:
        - dev
      variables:
        - $TESTS_TO_RUN =~ /test-scw-whole-enchilada/
        - $TESTS_TO_RUN =~ /test-scw-all/
        - $TESTS_TO_RUN =~ /test-all/
    artifacts:
      when: always
      reports:
        junit: $CI_PROJECT_DIR/cloned-engine/results.xml
      paths:
        - $CI_PROJECT_DIR/gitlab-log-utilities
        - $CI_PROJECT_DIR/.qovery-workspace
      expire_in: 2 week
    interruptible: true

scw-infra:
  stage: tests
  retry: 0
  timeout: 3 hours
  script:
    - ./helper.sh scw_infra
  dependencies:
    - build-and-lint
  when: always
  tags:
    - vm-2cpu-4gmem-0g
  only:
    refs:
      - dev
    variables:
      - $TESTS_TO_RUN =~ /test-scw-infra/
      - $TESTS_TO_RUN =~ /test-scw-all/
      - $TESTS_TO_RUN =~ /test-all/
  artifacts:
    when: always
    reports:
      junit: $CI_PROJECT_DIR/cloned-engine/results.xml
    paths:
      - $CI_PROJECT_DIR/gitlab-log-utilities
      - $CI_PROJECT_DIR/.qovery-workspace
    expire_in: 2 week
  interruptible: true

scw-managed-services:
  stage: tests
  retry: 0
  timeout: 3 hours
  script:
    - ./helper.sh scw_managed_services
  dependencies:
    - build-and-lint
  tags:
    - vm-2cpu-4gmem-0g
  when: always
  only:
    refs:
      - dev
    variables:
      - $TESTS_TO_RUN =~ /test-scw-managed-services/
      - $TESTS_TO_RUN =~ /test-scw-all/
      - $TESTS_TO_RUN =~ /test-all/
  artifacts:
    when: always
    reports:
      junit: $CI_PROJECT_DIR/cloned-engine/results.xml
    paths:
      - $CI_PROJECT_DIR/gitlab-log-utilities
      - $CI_PROJECT_DIR/.qovery-workspace
    expire_in: 2 week
  interruptible: true

scw-self-hosted:
  stage: tests
  retry: 0
  timeout: 3 hours
  script:
    - ./helper.sh scw_self_hosted
  dependencies:
    - build-and-lint
  tags:
    - vm-2cpu-4gmem-0g
  when: always
  only:
    refs:
      - dev
    variables:
      - $TESTS_TO_RUN =~ /test-scw-self-hosted/
      - $TESTS_TO_RUN =~ /test-scw-all/
      - $TESTS_TO_RUN =~ /test-all/
  artifacts:
    when: always
    reports:
      junit: $CI_PROJECT_DIR/cloned-engine/results.xml
    paths:
      - $CI_PROJECT_DIR/gitlab-log-utilities
      - $CI_PROJECT_DIR/.qovery-workspace
    expire_in: 2 week
  interruptible: true

upgrade-engine-dev:
  stage: upgrade-dev
  retry: 1
  before_script:
    - apk add bash
  script:
    - $ROLLBACK_IMAGE=$(kubectl -n qovery get statefulset qovery-engine -ojson | jq --raw-output .spec.template.spec.containers[0].image)
    - ./helper.sh upgrade_on_dev || ./helper.sh downgrade_on_dev $ROLLBACK_IMAGE
  tags:
    - vm-1cpu-1gmem-0g
  when: manual
  only:
    refs:
      - dev

e2e-tests:
  stage: e2e-tests
  image: golang:1.16-alpine
  allow_failure: true
  dependencies:
    - upgrade-engine-dev
  tags:
    - vm-2cpu-2gmem-0g
  before_script:
    - apk add bash
    - echo -e "machine gitlab.com\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc
    - ./helper.sh await_docker
  script:
    - apk add --no-cache git build-base
    - mkdir /usr/local/qovery
    - cd /usr/local/qovery
    - git clone https://gitlab.com/qovery/quality-streets.git
    - cd quality-streets/e2e_tests/test
    - go test -timeout 1800s -v
  only:
    refs:
      - dev

downgrade-engine-dev:
  stage: downgrade-dev
  retry: 1
  dependencies:
    - e2e-tests
  before_script:
    - apk add bash
  script:
    - ./helper.sh downgrade_on_dev $ROLLBACK_IMAGE
  tags:
    - vm-1cpu-1gmem-0g
  when: manual
  only:
    refs:
      - dev

#
# Main branch
#

gitguardian:
  stage: release
  image: gitguardian/ggshield:latest
  retry: 0
  when: always
  script: ggshield scan ci
  tags:
    - vm-250mcpu-1gmem-0g
  only:
    refs:
      - main

release-image:
  stage: release
  retry: 1
  script:
    - ./helper.sh new_release
  tags:
    - bm-7cpu-12gmem-0g
  only:
    refs:
      - main

1-set-ga:
  stage: deploy
  retry: 2
  script:
    - ./helper.sh set_release_ga
  tags:
    - vm-250mcpu-1gmem-0g
  only:
    refs:
      - main
  when: manual

2-qovery-infra-engine-deploy:
  stage: deploy
  retry: 0
  script:
    - ./helper.sh deploy_engines_infra
  tags:
    - vm-250mcpu-1gmem-0g
  only:
    refs:
      - main
  when: manual

3-client-infra-deploy:
  stage: deploy
  retry: 0
  script:
    - ./helper.sh deploy_all_clusters
  tags:
    - vm-250mcpu-1gmem-0g
  only:
    refs:
      - main
  when: manual

4-qovery-env-engines:
  stage: deploy
  retry: 0
  script:
    - ./helper.sh deploy_engines_envs
  tags:
    - vm-250mcpu-1gmem-0g
  only:
    refs:
      - main
  when: manual
