image: qoveryrd/ci:9316db935438cb40a1e722d2af24a1efcff61b43

services:
  - docker:dind

stages:
  - tests
  - build
  - release
  - set_ga

before_script:
  - test -z $KUBERNETES_PORT || export DOCKER_HOST=tcp://127.0.0.1:2375

wip-fast-tests:
  stage: tests
  retry: 0
  script:
    - ./helper.sh fast_tests
  except:
    refs:
      - dev
      - master

wip-full-tests:
  stage: tests
  retry: 0
  script:
    - ./helper.sh all_tests
  when: manual
  except:
    refs:
      - dev
      - master

dev-full-tests:
  stage: tests
  retry: 0
  script:
    - ./helper.sh all_tests
  only:
    refs:
      - dev

dev-build:
  stage: build
  retry: 1
  script:
    - ./helper.sh build_image
  when: manual
  only:
    refs:
      - dev

dev-release:
  stage: release
  retry: 1
  script:
    - ./helper.sh new_release
  when: manual
  only:
    refs:
      - dev

master-build:
  stage: build
  retry: 0
  script:
    - ./helper.sh build_image
  only:
    refs:
      - master

master-release:
  stage: release
  retry: 1
  script:
    - ./helper.sh new_release
  only:
    refs:
      - master

master-set-ga:
  stage: set_ga
  retry: 2
  script:
    - ./helper.sh set_release_ga
  when: manual
  only:
    refs:
      - master
