[package]
name = "qovery-engine"
version = "0.1.0"
authors = ["Romaric Philogene <romaric@qovery.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.11"
cmd_lib = "0.7.8"
git2 = "0.13.6"
tempdir = "0.3.7"

# Docker deps
# shiplift = "0.6.0"

# AWS deps
tokio = "0.2.21"
rusoto_core = "0.44.0"
rusoto_sts = "0.44.0"
rusoto_credential = "0.44.0"
rusoto_ecr = "0.44.0"
rusoto_eks = "0.44.0"