# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# THIS DOCKERFILE IS FOR LOCAL USAGE ONLY
# DO NOT USE IT TO PUSH FINAL IMAGE ON PUBLIC DOCKER REPOSITORY
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# docker build stage
FROM rust:1.45-slim-buster as build

RUN apt-get update && apt-get -y install make libfindbin-libs-perl
WORKDIR /usr/src/app
ADD . .

# run tests
#RUN cargo test --workspace
# run release build
RUN cargo build --release

FROM debian:buster-slim as run

RUN groupadd -g 1000 qovery && \
    useradd --home-dir /home/qovery --gid 1000 --uid 1000 -m -s /bin/bash qovery

WORKDIR /home/qovery
COPY --from=build /usr/src/app/target/release/app .
COPY --from=build /usr/src/app/lib ./lib

RUN chown -Rf qovery. . && chmod 500 app
USER qovery
CMD ["./app"]
