apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qovery-engine
  namespace: qovery
  labels:
    app.kubernetes.io/instance: qovery-engine
    app.kubernetes.io/name: qovery-engine
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: qovery-engine
      app.kubernetes.io/name: qovery-engine
  namespaceSelector:
    matchNames:
      - "qovery"
  endpoints:
  - port: "metrics"
    interval: 30s
    scrapeTimeout: 5s
---
apiVersion: v1
kind: Service
metadata:
  name: qovery-engine
  namespace: qovery
  labels:
    app.kubernetes.io/instance: qovery-engine
    app.kubernetes.io/name: qovery-engine
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/instance: qovery-engine
