{
 "title": "AWS limits",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "query": "aws_autoscaling_used_total{resource=\"Auto Scaling groups\"}"
   }
  ]
 },
 "panels": [
  { "title": "EC2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Auto scaling",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_autoscaling_used_total{region=\"$region\"}",
     "legendFormat": "Used {{resource}}"
    },
    {
     "expr": "aws_autoscaling_limit_total{region=\"$region\"}",
     "legendFormat": "Limit {{resource}}"
    }
   ]
  },
  {
   "title": "Cloudformation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_cloudformation_limit_total{region=\"$region\"}",
     "legendFormat": "Used {{resource}}"
    },
    { "expr": "aws_cloudformation_used_total", "legendFormat": "Limit {{resource}}" }
   ]
  },
  {
   "title": "EC2",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aws_ec2_limit_total{region=\"$region\"}",
     "legendFormat": "Limit {{resource}}"
    },
    {
     "expr": "aws_ec2_used_total{region=\"$region\"}",
     "legendFormat": "Used {{resource}}"
    },
    {
     "expr": "aws_ec2_used_total{region=\"$region\"} / aws_ec2_limit_total{region=\"$region\"} * 100",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "EBS",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aws_ebs_used_total{region=\"$region\"} / aws_ebs_limit_total{region=\"$region\"} * 100",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  { "title": "Databases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "DynamoDB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_dynamodb_limit_total{region=\"$region\"}",
     "legendFormat": "Limit {{resource}}"
    },
    {
     "expr": "aws_dynamodb_used_total{region=\"$region\"}",
     "legendFormat": "Used {{resource}}"
    }
   ]
  },
  {
   "title": "RDS",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aws_rds_used_total{region=\"$region\"} / aws_rds_limit_total{region=\"$region\"} * 100",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "ELB",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aws_elb_used_total{region=\"$region\"} / aws_elb_limit_total{region=\"$region\"} * 100"
    }
   ]
  },
  {
   "title": "VPC",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aws_vpc_used_total{region=\"$region\"} / aws_vpc_limit_total{region=\"$region\"} * 100",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Route53",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aws_route53_limit_total", "legendFormat": "Limit {{resource}}" },
    { "expr": "aws_route53_used_total", "legendFormat": "Used {{resource}}" }
   ]
  },
  { "title": "Others", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "IAM",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aws_iam_used_total / aws_iam_limit_total * 100",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "SES",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_ses_limit_total{region=\"$region\"}",
     "legendFormat": "Limit {{resource}}"
    },
    {
     "expr": "aws_ses_used_total{region=\"$region\"}",
     "legendFormat": "Used {{resource}}"
    }
   ]
  }
 ]
}