{
 "title": "Engine",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({container=\"qovery-engine\"})[5m])",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Panic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({container=\"qovery-engine\"})[5m] |= \"A task caused a panic while executing!\")",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{container=\"qovery-engine\"}"
    }
   ]
  }
 ]
}