[package]
name = "qovery-engine-task-manager"
version = "0.1.0"
authors = ["Romaric Philogene <evoxmusic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qovery-engine = { path = "../cloned-engine" }
crossbeam-channel = "0.5.0"
evmap = "10.0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.19"
log = "0.4.11"
