[package]
name = "qovery-engine-task-manager"
version = "0.1.0"
authors = ["Romaric Philogene <evoxmusic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qovery-engine = { path = "../qovery-engine" }
crossbeam-channel = "0.4.2"
evmap = "11.0.0-alpha.1"
uuid = { version = "0.8", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.11"
log = "0.4.8"