[package]
name = "app"
version = "0.1.0"
authors = ["Romaric Philogene <evoxmusic@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "engine_grpc"
path = "src/main_grpc.rs"

[features]
default = []

# To split from unit tests
unit-tests = []
test-functional = []
test-full = ["test-functional"]


[dependencies]
qovery-engine = { path = "../lib-engine" }
crossbeam-channel = "0.5.8"
serde_json = "1.0.120"
uuid = { version = "1.10.0", features = ["v4", "serde"] }
chrono = "0.4.38"
ctrlc = { version = "3.4.1", features = ["termination"] } # sig term handler wrapper
retry = "2.0.0"
dirs = "5.0.1"
url = "2.5.2"
regex = "1"
anyhow = "1.0.86"
scopeguard = "1.2.0"
reqwest = { version = "0.12.5", features = ["blocking", "json", "gzip"] }
serde = "1.0.188"
clap = { version = "4.5.9", features = ["derive", "env"]}

# Webserver (For Prometheus, Healthcheck, ...)
tokio = { version = "1.38.1", features = ["full"] }
tokio-stream = "0.1.15"
warp = "0.3.7"
once_cell = "1.19.0"
prometheus = { git = "https://github.com/tikv/rust-prometheus", rev = "ac86a264223c8d918a43e739ca3c48bb4aaedb90", features = ["process"] }

# Kubernetes
kube = { version = "0.93.1", features = ["default"] }
k8s-openapi = { version = "0.22.0", default-features = false, features = ["v1_27"] }

# GRPC
tonic = { version = "0.12.1", features = ["tls", "tls-roots", "zstd", "transport"] }
prost = "0.13.1"
prost-types = "0.13.1"
tower = "0.5.0"
futures-util = "0.3.28"

# tracing
tracing = { version = "0.1.37", features = ["log"] }
tracing-futures = { version = "0.2.5", features = ["futures-03"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "fmt", "local-time"] }
tracing-appender = "0.2.3"

# To load .env file into env variables
dotenv = "0.15.0"
# To get build info (commit, version, ...) at runtime
shadow-rs = { version = "0.33.0", features = [] }

[dev-dependencies]
reqwest = { version = "0.12.5", features = ["blocking"] }
hyper-util = {  version = "0.1.7", features = ["tokio"] }
tower = { version = "0.5.0", features = ["util"] }


[build-dependencies]
tonic-build = { version = "0.12.1", features = ["prost"] }
shadow-rs = { version = "0.33.0", features = [] }