[package]
name = "app"
version = "0.1.0"
authors = ["Romaric Philogene <evoxmusic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

# To split from unit tests
unit-tests = []
test-functional = []
test-full = ["test-functional"]


[dependencies]
qovery-engine = { path = "../cloned-engine" }
crossbeam-channel = "0.5.0"
nats = "0.8.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["v4", "serde"] }
chrono = "0.4.19"
ctrlc = { version = "3.1.4", features = ["termination"] } # sig term handler wrapper
retry = "1.0.0"
dirs = "3.0.1"
openssl-sys = "0.9"
openssl = { version = "0.10", features = ["vendored"] }
evmap = "10.0.2"

# Webserver (For Prometheus, Healthcheck, ...)
tokio = { version = "1.1.0", features = ["net", "rt-multi-thread"] }
warp = "0.3.0"
lazy_static = "1.4.0"
prometheus = { git = "https://github.com/tikv/rust-prometheus", rev = "ac86a264223c8d918a43e739ca3c48bb4aaedb90", features = ["process"] }

# tracing
tracing = { version = "0.1.26", features = ["log"] }
tracing-subscriber = { version = "0.2.18", features = ["env-filter"] }

# To load .env file into env variables
dotenv = "0.15.0"

[dev-dependencies]
reqwest = { version = "0.10.8", features = ["blocking"] }


