[package]
name = "app"
version = "0.1.0"
authors = ["Romaric Philogene <evoxmusic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qovery-engine = { git = "https://github.com/Qovery/engine", rev = "fefd46c9d55df8d975b4bf69c3f71a350a93a162" }
qovery-engine-shared = { path = "../qovery-engine-shared" }
qovery-engine-task-manager = { path = "../qovery-engine-task-manager" }
crossbeam-channel = "0.4.4"
nats = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["v4"] }
chrono = "0.4.13"
ctrlc = { version = "3.1.4", features = ["termination"] } # sig term handler wrapper
retry = "1.0.0"
dirs = "3.0.1"
openssl-sys = "0.9"
openssl = { version = "0.10", features = ["vendored"] }

# logger
env_logger = "0.7.1"
log = "0.4.8"
