use crate::environment::action::DeploymentAction;
use crate::environment::action::deploy_helm::{HelmChartValues, HelmDeployment};
use crate::environment::action::pause_service::PauseServiceAction;
use crate::environment::models::application::{Application, ApplicationService};
use crate::environment::models::types::{CloudProvider, ToTeraContext};
use crate::environment::report::application::reporter::ApplicationDeploymentReporter;
use crate::environment::report::execute_long_deployment;
use crate::errors::EngineError;
use crate::events::{EnvironmentStep, Stage};
use crate::helm::{ChartInfo, HelmAction, HelmChartNamespaces};
use crate::infrastructure::models::cloud_provider::DeploymentTarget;
use crate::infrastructure::models::cloud_provider::service::{Action, Service};

use super::utils::{delete_nlb_or_alb_service, validate_deployment_storage_replicas};
use crate::environment::action::deploy_external_secrets::{
    clean_unused_secrets_generated_by_eso, uninstall_service_external_secret,
};
use crate::environment::action::restart_service::RestartServiceAction;
use crate::environment::report::logger::EnvProgressLogger;
use crate::infrastructure::models::kubernetes::Kind;
use std::path::PathBuf;
use std::time::Duration;
use tera::Context;

impl<T: CloudProvider> DeploymentAction for Application<T>
where
    Application<T>: ToTeraContext,
{
    fn on_create(&self, target: &DeploymentTarget) -> Result<(), Box<EngineError>> {
        let long_task = |_logger: &EnvProgressLogger| -> Result<(), Box<EngineError>> {
            let event_details = self.get_event_details(Stage::Environment(EnvironmentStep::Deploy));
            // If the service have been paused, we must ensure we un-pause it first as hpa will not kick in
            let _ = PauseServiceAction::new(
                self.kube_label_selector(),
                false,
                Duration::from_secs(5 * 60),
                event_details.clone(),
                true,
            )
            .unpause_if_needed(target);

            if !self.storages.is_empty() {
                validate_deployment_storage_replicas(self.min_instances, self.max_instances, &event_details)?;
            }

            let chart = ChartInfo {
                name: self.helm_release_name(),
                path: self.workspace_directory().to_string(),
                namespace: HelmChartNamespaces::Custom(target.environment.namespace().to_string()),
                timeout_in_seconds: self.startup_timeout().as_secs() as i64,
                k8s_selector: Some(self.kube_label_selector()),
                ..Default::default()
            };

            let helm = HelmDeployment::new(
                event_details.clone(),
                self.to_tera_context(target)?,
                PathBuf::from(self.helm_chart_dir()),
                HelmChartValues::SerializedContext,
                chart,
            );

            if target.kubernetes.kind() == Kind::Eks {
                delete_nlb_or_alb_service(
                    target.kube.clone(),
                    target.environment.namespace(),
                    format!("qovery.com/service-id={}", self.long_id()).as_str(),
                    target.kubernetes.advanced_settings().aws_eks_enable_alb_controller,
                    event_details,
                )?;
            }

            let result = helm.on_create(target);

            // Clean unused secret generated by ESO
            if result.is_ok() {
                let service_eso_secret_names: Vec<String> = self
                    .external_secrets
                    .iter()
                    .map(|group| group.secret_name.to_string())
                    .collect();
                clean_unused_secrets_generated_by_eso(
                    target.kube.client(),
                    target.environment.namespace(),
                    &self.long_id,
                    service_eso_secret_names,
                );
            }

            result
        };

        execute_long_deployment(ApplicationDeploymentReporter::new(self, target, Action::Create), long_task)
    }

    fn on_pause(&self, target: &DeploymentTarget) -> Result<(), Box<EngineError>> {
        execute_long_deployment(
            ApplicationDeploymentReporter::new(self, target, Action::Pause),
            |_logger: &EnvProgressLogger| -> Result<(), Box<EngineError>> {
                let pause_service = PauseServiceAction::new(
                    self.kube_label_selector(),
                    false,
                    Duration::from_secs(5 * 60),
                    self.get_event_details(Stage::Environment(EnvironmentStep::Pause)),
                    true,
                );
                pause_service.on_pause(target)
            },
        )
    }

    fn on_delete(&self, target: &DeploymentTarget) -> Result<(), Box<EngineError>> {
        let event_details = self.get_event_details(Stage::Environment(EnvironmentStep::Delete));
        execute_long_deployment(
            ApplicationDeploymentReporter::new(self, target, Action::Delete),
            |logger: &EnvProgressLogger| {
                let chart = ChartInfo {
                    name: self.helm_release_name(),
                    namespace: HelmChartNamespaces::Custom(target.environment.namespace().to_string()),
                    action: HelmAction::Destroy,
                    k8s_selector: Some(self.kube_label_selector()),
                    ..Default::default()
                };
                let helm = HelmDeployment::new(
                    event_details.clone(),
                    Context::default(),
                    PathBuf::from(self.helm_chart_dir().as_str()),
                    HelmChartValues::SerializedContext,
                    chart,
                );

                helm.on_delete(target)?;

                // Delete shared container repository if needed (depending on flag computed on core)
                if self.should_delete_shared_registry() {
                    logger.info("🪓 Terminating shared container registry of the application".to_string());
                    if let Err(err) = target
                        .container_registry
                        .delete_repository(self.build().image.shared_repository_name())
                    {
                        let safe_user_msg =
                            "❌ Failed to delete shared container registry of the application".to_string();
                        let user_error = EngineError::new_engine_error(
                            EngineError::new_container_registry_error(event_details.clone(), err),
                            safe_user_msg,
                            None,
                        );
                        return Err(Box::new(user_error));
                    }
                }

                // Delete container repository created for this application
                logger.info("🪓 Terminating container registry of the application".to_string());
                if let Err(err) = target
                    .container_registry
                    .delete_repository(self.build().image.legacy_repository_name())
                {
                    let safe_user_msg = "❌ Failed to delete container registry of the application".to_string();
                    let user_error = EngineError::new_engine_error(
                        EngineError::new_container_registry_error(event_details.clone(), err),
                        safe_user_msg,
                        None,
                    );
                    return Err(Box::new(user_error));
                }

                // Delete external secrets helm release if exists
                uninstall_service_external_secret(&self.kube_name, self.long_id(), target);

                Ok(())
            },
        )
    }

    fn on_restart(&self, target: &DeploymentTarget) -> Result<(), Box<EngineError>> {
        execute_long_deployment(
            ApplicationDeploymentReporter::new(self, target, Action::Restart),
            |_logger: &EnvProgressLogger| -> Result<(), Box<EngineError>> {
                let restart_service = RestartServiceAction::new(
                    self.kube_label_selector(),
                    false,
                    self.get_event_details(Stage::Environment(EnvironmentStep::Restart)),
                );
                restart_service.on_restart(target)
            },
        )
    }
}
