pub const TF_PLUGIN_CACHE_DIR: &str = "TF_PLUGIN_CACHE_DIR";
pub const AWS_ACCESS_KEY_ID: &str = "AWS_ACCESS_KEY_ID";
pub const AWS_SECRET_ACCESS_KEY: &str = "AWS_SECRET_ACCESS_KEY";
pub const AWS_DEFAULT_REGION: &str = "AWS_DEFAULT_REGION";
pub const KUBECONFIG: &str = "KUBECONFIG";
pub const SCW_ACCESS_KEY: &str = "SCW_ACCESS_KEY";
pub const SCW_SECRET_KEY: &str = "SCW_SECRET_KEY";
pub const SCW_DEFAULT_PROJECT_ID: &str = "SCW_DEFAULT_PROJECT_ID";
