pub const TF_PLUGIN_CACHE_DIR: &str = "TF_PLUGIN_CACHE_DIR";
pub const AWS_ACCESS_KEY_ID: &str = "AWS_ACCESS_KEY_ID";
pub const AWS_SECRET_ACCESS_KEY: &str = "AWS_SECRET_ACCESS_KEY";
pub const AWS_DEFAULT_REGION: &str = "AWS_DEFAULT_REGION";
pub const KUBECONFIG: &str = "KUBECONFIG";
pub const SCALEWAY_ACCESS_KEY: &str = "SCALEWAY_ACCESS_KEY";
pub const SCALEWAY_SECRET_KEY: &str = "SCALEWAY_SECRET_KEY";
pub const SCALEWAY_DEFAULT_PROJECT_ID: &str = "SCALEWAY_DEFAULT_PROJECT_ID";
