syntax = "proto3";

import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/empty.proto";

option go_package = "qovery-engine/proto";
option java_multiple_files = true;
option java_package = "com.qovery.lib.grpc";
option java_outer_classname = "EngineProto";

package engine;

service Engine {
  rpc IsAuthorized(google.protobuf.Empty) returns (google.protobuf.Empty) {}
  rpc GetNewDeployment(DeploymentRequest) returns (DeploymentInfo) {}
  rpc ExecDeployment(stream EngineMessageTx) returns (stream EngineMessageRx) {}

  rpc GetServiceVersion(ServiceVersionRequest) returns (ServiceVersionResponse) {}
  rpc GetGitToken(GitTokenRequest) returns (GitTokenResponse) {}
}

enum DeploymentType {
  Unknown = 0; // empty value in proto map to 0
  Environment = 1;
  Infrastructure = 2;
}

message DeploymentRequest {
  DeploymentType deployment_type = 1;
}

enum StepLabel {
  Step_Label_Service = 0;
  Step_Label_Environment = 1;
}

enum StepStatus {
  NotSet = 0;
  Success = 1;
  Error = 2;
  Cancel = 3;
  Skip = 4;
}

message StepRecord {
  string step_name = 1;
  StepLabel step_label = 2;
  string id = 3;
  google.protobuf.Duration duration = 4;
  StepStatus status = 5;
}

message Metrics {
  StepRecord step_record = 1;
}

message DeploymentInfo {
  string organization_id = 1;
  string cluster_id = 2;
  string execution_id = 3;
  string request_id = 4;
  DeploymentType type = 5;
  string last_message_id = 6;
}

message EngineMessageTx {
  google.protobuf.Timestamp message_id = 3;
  oneof message {
    DeploymentInfo deployment_request = 1;
    string log = 2;
    Metrics metrics = 4;
  }
}

message EngineMessageRx {
  string message_id = 1;
  oneof request {
    string deployment_request = 2;
    int32 deployment_cancel = 3;
    bool terminated = 4;
  }
}


enum EngineServiceType {
  UNKNOWN = 0; // empty value in proto map to 0
  SHELL_AGENT = 1;
  CLUSTER_AGENT = 2;
  ENGINE = 3;
}

message ServiceVersionRequest {
  string jwt_token = 1;
  EngineServiceType service_type = 2;
}

message ServiceVersionResponse {
  string version = 1;
}



enum ServiceType {
  UNKNOWN_SRV = 0; // empty value in proto map to 0
  APPLICATION = 1;
  JOB = 2;
  HELM_CHART = 3;
}

message GitTokenRequest {
  string jwt_token = 1;
  ServiceType service_type = 2;
  string service_id = 3;
}

message GitTokenResponse {
  string login = 1;
  string accessToken = 2;
  string expiredAt = 3;
}
